import pytest
import time
from app.services.token_counter import TokenCounter

@pytest.fixture
def token_counter_service():
    return TokenCounter()

def test_performance_short_text(token_counter_service):
    """Test performance with short text."""
    text = "Hello world! This is a short text."
    
    start_time = time.time()
    result = token_counter_service.count_tokens(text, "gpt-3.5-turbo")
    end_time = time.time()
    
    # For short texts, should be well under 100ms
    assert (end_time - start_time) * 1000 < 100
    assert result["processing_time_ms"] < 100

def test_performance_medium_text(token_counter_service):
    """Test performance with medium-sized text (a few paragraphs)."""
    # Generate a medium-sized text
    text = " ".join(["This is paragraph number " + str(i) + ". It contains some sample text that will be tokenized. " * 3 
                    for i in range(5)])
    
    start_time = time.time()
    result = token_counter_service.count_tokens(text, "gpt-3.5-turbo")
    end_time = time.time()
    
    # Should still be relatively fast
    assert (end_time - start_time) * 1000 < 100
    
def test_performance_long_text(token_counter_service):
    """Test performance with a longer text (10,000+ characters)."""
    # Generate a long text
    text = "This is a sample sentence that will be repeated. " * 200  # ~10,000 characters
    
    start_time = time.time()
    result = token_counter_service.count_tokens(text, "gpt-3.5-turbo")
    end_time = time.time()
    
    # Should complete in under 100ms for 10,000 characters as per spec
    assert (end_time - start_time) * 1000 < 100

def test_batch_performance(token_counter_service):
    """Test performance of batch processing."""
    # Create 10 sample texts
    texts = [{"text": f"This is sample text number {i}.", "text_id": f"text{i}"} for i in range(10)]
    
    start_time = time.time()
    results = token_counter_service.batch_count_tokens(texts, "gpt-3.5-turbo")
    end_time = time.time()
    
    total_time_ms = (end_time - start_time) * 1000
    
    # Batch processing should be efficient
    assert total_time_ms < 100
    assert len(results) == 10

# Generated by Copilot
